### ISSUE TITLE
HW Tasks

### ISSUE THREAD

**Issue by gcerb** [gcerb/SSW345_HW1#1]
### To-Do List

- [ ] **Task 1**: Finish HW 1 assignment. 
- [ ] **Task 2**: Make sure to submit a link to this GitHub repo in the pdf submission.
- [ ] **Task 3**: Pdf submission should include the Team Chapter and GitHub HW chapter with link.
- [ ] **Task 4**: Look over lecture slides for next class.
- [ ] **Task 5**: Look at next upcoming assignment.
